name: CI Build

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages list
        run: sudo apt update

      - name: Install gcc, g++, CMake, Make, SFML, OpenGL, GLM, GLEW, Doxygen, Graphviz
        run: sudo apt install -y gcc g++ cmake make libsfml-dev libglew-dev libglm-dev mesa-common-dev libgl1-mesa-dev doxygen graphviz

      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Doxygen GitHub Pages Deploy Action
        uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs/html
          config_file: Doxyfile
