name: CI

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages list
        run: sudo apt update

      - name: Install gcc, g++, clang-tidy, CMake, Make, SFML, OpenGL, GLM, GLEW, Doxygen
        run: >
          sudo apt install -y
          gcc
          g++
          clang-tidy
          cmake
          make
          libsfml-dev
          libglew-dev
          libglm-dev
          mesa-common-dev
          libgl1-mesa-dev
          doxygen

      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Build Documentation
        run: cmake --build ${{github.workspace}}/build --target documentation
        
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/build/html